name: Build LaTeX document
on: 
  push:
    paths-ignore:
      - paper.pdf
  schedule:
    - cron: '0 22 * * *'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Rename PDF file
        run: mv main.pdf paper.pdf
      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f paper.pdf
          git commit -m "📄✨ docs: automatic update bachelor project paper with latest changes ✨📄" -a
          git push
      
            
